version: '2.1'
services:
  core:
    image: amina:latest
    container_name: amina_core
    expose:
      - "3454"
    ports:
      - "3454:3454"
    working_dir: /usr/share/amina
    command: npm run start
    restart: always
    depends_on:
      - test
    mem_limit: 4G
  test:
    image: amina:latest
    container_name: amina_test
    working_dir: /usr/share/amina
    command: npm run test
  dev:
    image: amina:latest
    container_name: amina_dev
    volumes:
      - ./core/:/amina
    expose:
      - "3454"
    ports:
      - "3454:3454"
    working_dir: /usr/share/amina
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    mem_limit: 4G