version: '3'
services:
  core:
    image: amina:latest
    container_name: amina_core
    ports:
      - 80:80
    working_dir: /usr/share/amina
    command: npm run start
    restart: always
    depends_on:
      - test
  test:
    image: amina:latest
    container_name: amina_test
    working_dir: /usr/share/amina
    command: npm run test
  dev:
    image: amina:latest
    container_name: amina_dev
    volumes:
      - ./core/:/amina
      - ./backup/:/backup
    working_dir: /amina
    entrypoint: /bin/sh
    stdin_open: true
    tty: true